### ISSUE TITLE
일정 예외처리에 대한 ControllerAdvice를 생성한다.

### ISSUE THREAD

**Issue by gudonghee2000** [woowacourse-teams/2022-dallog#125]
## 🤷 구현할 기능
일정 예외처리에 대한 ControllerAdvice를 생성한다.

## 🔨 상세 작업 내용

- [ ] 일정에 대한 ControllerAdvice 생성

## ⏰ 예상 소요 기간
1시간

**Comment by devHudi** [comment]
#146 와 중복이므로 닫습니다.
