### ISSUE TITLE
카테고리 생성 시 해당 카테고리 구독을 요청한다.

### ISSUE THREAD

**Issue by daaaayeah** [woowacourse-teams/2022-dallog#249]
## 🤷 구현할 기능

카테고리 생성 시 해당 카테고리 구독을 요청한다.

## ⏰ 예상 소요 기간

0.5시간

**Comment by devHudi** [comment]
(참고) 임시로 프론트에서 요청하기로 결정하였고, #243 PR이 머지되면 프론트엔드에서 본 기능을 제거하기로 결정했습니다!
