### ISSUE TITLE
카테고리 탐색시 생성한 사람등의 부가정보를 표시한다.

### ISSUE THREAD

**Issue by gudonghee2000** [woowacourse-teams/2022-dallog#281]
## 🤷 구현할 기능

카테고리 탐색시 카테고리 제목 이외의 부가정보를 표시

## ⏰ 예상 소요 기간
2시간

**Comment by daaaayeah** [comment]
#319 PR에서 구현되었으므로 해당 이슈는 close 하겠습니다
