### ISSUE TITLE
카테고리 생성 기능을 구현한다.

### ISSUE THREAD

**Issue by devHudi** [woowacourse-teams/2022-dallog#34]
## 🤷 구현할 기능

카테고리 생성 기능을 구현한다.

## 🔨 상세 작업 내용

- [x] 카테고리 조회 API 설계
- [x] 카테고리 Entity 설계
- [x] 카테고리 생성 인수테스트 작성
- [x] 카테고리 생성 기능 구현
- [ ] #45

## ⏰ 예상 소요 기간

8시간

**Comment by summerlunaa** [comment]
### 카테고리 Entity 설계

- name (이름) : 20자, null X, blank X
- createdAt (생성일시)
- creator (생성자) -> 유저 구현되면 추가

**Comment by summerlunaa** [comment]
카테고리 생성 인수테스트 작성 시 생긴 의문
- `상태코드_200이_반환된다` & `상태코드_201이_반환된다` 메서드가 겹치는데 어떻게 중복 코드를 줄일 수 있을까? `AcceptanceTest`에 넣나?
-
