### ISSUE TITLE
전체 카테고리 조회 기능을 구현한다.

### ISSUE THREAD

**Issue by devHudi** [woowacourse-teams/2022-dallog#35]
## 🤷 구현할 기능

전체 카테고리 조회 기능을 구현한다.

## 🔨 상세 작업 내용

- [x] 카테고리 전체 조회 API 설계
- [x] 카테고리 조회 인수테스트 작성
- [x] 카테고리 조회 기능 구현
- [x] 무한스크롤을 위한 슬라이싱(페이징) 기능을 구현한다.
- [ ] #57

## ⏰ 예상 소요 기간

2시간

**Comment by summerlunaa** [comment]
## 페이징 고민

프론트에서는 페이지가 1부터 시작하지만 백엔드에서는 0부터 시작해서 1을 빼줘야 합니다. 이 로직을 어디서 어떻게 처리할까요?

고민해봤는데, ArgumentResolver를 사용하는 것이 좋겠다는 생각이 드네요. 그럼 바로 PageRequest를 컨트롤러에서 받을 수 있고 1을 빼주는 로직도 사라지겠네요. 대신 Spring Data에 대한 의존성이 생기긴 하는데, 저는 이 방법이 더 좋은 것 같은데 어떻게 생각하시나요?

@devHudi @hyeonic @gudonghee2000

**Comment by hyeonic** [comment]
`ArgumentResolver`는 생각지 못한 방법인데요! 파랑이 생각했을 때 ArgumentResolver의 역할에 대해 어떻게 생각하시나요?

**Comment by summerlunaa** [comment]
`ArgumentResolver`는 컨트롤러에 요청이 들어왔을 때, 요청에 들어온 값으로부터 원하는 객체를 만들어내는 역할을 한다고 생각해요!
페이지 요청에 대한 시작 인덱스가 달라 매번 1을 빼줘야 한다면 `ArgumentResolver`를 통해 시작 인덱스를 0으로 맞추고 PageRequest 객체를 만들어서 넘겨주는 것이 어떨까요? 중복을 줄이고 인덱스 변경에 대한 책임을 덜 수 있을 것 같습니다~

**Comment by summerlunaa** [comment]
흠 하지만 추후에 정렬이 추가될 상황을 고려하면 `ArgumentResolver`는 유연하지 못한 구조가 될 수도 있겠네요🧐 우선 좀 더 고민해보겠습니다. 다른 분들도 의견 남겨주세요!
