### ISSUE TITLE
Logback File Appender를 비동기로 변경한다.

### ISSUE THREAD

**Issue by devHudi** [woowacourse-teams/2022-dallog#623]
## 🤷 구현할 기능

현재 Logback 이 로그 파일을 생성하는 작업이 동기로 동작하고 있어서 로그 생성이 병목이 될것으로 예상되고 있습니다.

이를 개선하고 실제 개선된 성능을 부하테스트를 통해 검증합니다.

## 🔨 상세 작업 내용

- [x] Logback 설정 변경
- [x] 전/후 부하 테스트를 통한 성능 개선 여부 확인

## ⏰ 예상 소요 기간

2시간

**Comment by summerlunaa** [comment]
## 결론: `적용하지 않기로 했습니다.`

### 문제 1. async가 잘 적용되었는지 확인할 수가 없다.

file log 기록하는 부분에 async를 적용했지만, 실제로 잘 적용되어 동작하는지 어떻게 확인하는지를 모르겠다. 

### 문제 2. 성능 측정 결과 차이가 없다.

async를 적용하기 전과, 적용한 후 각각 부하테스트를 진행했다. 하지만 차이가 거의 없었다.

왜 차이가 나지 않는지 정확히 알 수 없었다.
