### ISSUE TITLE
FCP(First Contentful Paint)를 개선한다.

### ISSUE THREAD

**Issue by jhy979** [woowacourse-teams/2022-dallog#636]
## 🤷 구현할 기능
FCP(First Contentful Paint)를 개선한다.

## 🔨 상세 작업 내용

- [ ] FCP(First Contentful Paint)를 개선한다.

## ⏰ 예상 소요 기간
1/2시간

**Comment by daaaayeah** [comment]
0.2s로 개선할 필요성을 느끼지 못해 개선하지 않기로 하였습니다 🙃

**Comment by daaaayeah** [comment]
0.2s로 개선할 필요성을 느끼지 못해 개선하지 않기로 하였습니다 🙃
