### ISSUE TITLE
1,000만명이 사용해도 서비스할 수 있도록 팀의 인프라 아키텍처 개선 방향을 고민한다.

### ISSUE THREAD

**Issue by devHudi** [woowacourse-teams/2022-dallog#716]
## 🤷 구현할 기능

1,000만명이 사용해도 서비스할 수 있도록 팀의 인프라 아키텍처 개선 방향을 고민한다.

## 🔨 상세 작업 내용

- [ ] 1,000만명이 사용해도 서비스할 수 있도록 팀의 인프라 아키텍처 개선 방향을 고민한다.
- [ ] 백엔드 4명의 의견을 모아서 하나의 설계를 만들어낸다.

**Comment by devHudi** [comment]
![image](https://user-images.githubusercontent.com/11745691/194894615-d280d169-46a0-4e4c-98ef-e6d1be8a4430.png)

뇌피셜과 행복회로 풀 가동했습니다. 아키텍처는 downtime을 줄여 가용성을 높이는것을 목표로 설계했어요.

1. 우선 Auth, Member, Category, Schedule 이 4개의 도메인별로 마이크로 서비스를 구성했습니다. 지금과 같은 모놀리식 구조에서는 Category 도메인에 문제가 생기면 Auth, Member, Schedule도 모두 사용할 수 없습니다. MSA에서는 Category 도메인에 문제가 생기면, 그 도메인만 사용할 수 없고, 다른 서비스의 기능은 정상적으로 사용할 수 있습니다.
2. 각 MSA 내부에서는 캐시 서버로 사용될 Nginx와 스프링부트 애플리케이션이 한 EC2 인스턴스로 묶여서 서비스됩니다. 이 EC2 인스턴스는 로드밸런서 (ELB or ALB) 에 묶여 부하분산 됩니다. 여기에 AWS Autoscaling을 적용해 특정 조건에 따라 자동으로 서버가 수평 확장 되도록 구성해볼 수 있습니다.
3. 데이터베이스는 Master - Slave 구조로 레플리케이션을 적용했습니다. 이렇게 데이터베이스를 다중화하여 읽기 쿼리를 분산하고, 성능 증가를 기대할 수 있습니다. 그림에는 없지만, 배치 작업을 돌려 주기적으로 특정 slave 에서 mysql dump 를 따서 백업할 수 있을 것이라 생각합니다. 또, 여기에 파티셔닝과 샤딩을 적용하면 더 좋겠죠?
4. 데이터베이스를 레플리케이션으로 다중화했는데, 여기에 MHA와 같은 auto failover 솔루션을 사용하여 장애 발생 시 감지하고 자동으로 장애 극복(failover) 할 수 있게 합니다. 이 부분은 키워드만 알아서 제대로는 잘 몰러유 😅
5. MSA에서 Auth, Category, Member, Schedule 끼리는 서로 API로 동기적으로 통신합니다. 하지만, (아직 없지만) Notification 서버와는 사이에 Kafka라는 메시지 큐를 두어 비동기로 통신합니다. 알림 도메인의 몇개정도 누락된다고 큰일나지 않으므로, 매우 높은 신뢰성을 확보할 필요가 없기 때문입니다.
6. Schedule 도메인에는 Elastic Search를 둡니다. 여기에는 서비스에서 활용되는 모든 일정 데이터를 저장합니다. 일정 데이터 특성상 쓰기보다는 읽기 요청이 압도적으로 많습니다. 이런 특성상 RDB를 사용하는 것보단 Elastic Search를 사용하는 것이 더 적합해보입니다. 일정 데이터외의 데이터만 RDB에 저장합니다. 
7. Schedule 도메인엔 또 Redis로 서버 캐시를 구성합니다. 여기에는 외부 캘린더(구글 등)에서 가져온 데이터를 임시로 저장합니다. TTL은 5분가량이 적당할 것 같습니다. 보안 문제상 사용자의 외부 캘린더 데이터를 저희 RDB에 저장하지 않고, 요청 시 그때그때 Google Calendar 쪽으로 API를 요청해 가져옵니다. 이를 일정시간 캐시하면 조회성능이 더 증가할 것이라고 생각됩니다.

**Comment by hyeonic** [comment]
우선 천만명이 사용하면 너무 행복할 것 같다. 

우선 우리는 하나의 데이터베이스를 활용하고 있다. 만약 스케일 아웃을 한 애플리케이션 서버가 늘어날 수록 한정된 커넥션을 가진 데이터베이스는 병목 현상이 일어나게 될 것이다. 데이터베이스의 쿼리 처리 시간을 조절 하던, 스케일 아웃을 하던 추가적인 조치가 필요하다.

데이터베이스의 쿼리 튜닝에 가장 중요한 부분은 바로 디스크 I/O를 줄이는 것이다. 디스크 I/O를 줄이는 방법으로는 인덱스를 적절히 활용하는 것이다. 

스케일 아웃하는 방법도 있다. 

- 파티셔닝
- 레플리케이션
- 클러스터링
- 샤딩
- …

우리는 데이터베이스의 일련의 비즈니스 로직을 트랜잭션 단위로 진행학하고 있다. 트랜잭션이 마무리되면 커넥션 풀에 커넥션을 반납하게 된다. 만약 이 트랜잭션 처리 시간이 길어질수록 커넥션을 얻기 위한 요청은 막연하게 기다릴 뿐이다.

이러한 트랜잭션 처리 시간을 최소화 하는 것도 수 많은 동시 요청을 감당할 수 있는 방법 중 하나이다. 병목이 생기는 지점을 잘 확인하고 사전에 대비한다.

애플리케이션 서버를 확장하는 것 vs 데이터베이스 서버를 확장하는 것

우선 순위가 높은 것은 데이터베이스라고 생각한다. 외부 리소스를 제외한 특정 요청에서 가장 오랜 시간이 걸리는 부분은 바로 데이터베이스와의 통신 시간이라 생각한다. 이러한 데이터베이스가 안정적으로 확장되어야 데이터베이스를 사용하는 애플리케이션도 부담없이 확장될 수 있다.

달록은 외부 리소스를 요청하여 사용하고 있다. 1000만명이 넘는 사용자가 사용할 경우 대부분의 사용자는 외부 리소스를 요청하게 될 것이다. 우리는 일정 정보를 얻기 위해 매번 외부 리소스 요청을 진행해야 한다.

외부 요청으로 부터 응답을 받기 까지의 시간이 추가적으로 소요된다. 그렇기 때문에 우리는 외부 요청에서 오는 데이터를 적절히 캐싱하여 추가적인 요청을 방지해야 한다.

이러한 캐시 서버는 redis를 활용할 수 있다. 특정 외부 캘린더 id를 기반으로 일정 정보를 캐싱하면 해당 캘린더를 구독한 사용자의 요청은 캐싱된 데이터를 재사용할 것이다. 다만 개인 일정의 경우 자신만 조회할 수 있기 때문에 캐싱이 무의미 해질 수 있다.

**Comment by summerlunaa** [comment]
- 1000만명이 사용하려면 물리적으로 로드 밸런싱을 지원해주는 L4 Switch를 사용해야할 것 같다.
- ngnix를 이용한 로드 밸런싱도 당연히 필요.
- DB 파티셔닝을 통해 월별로 테이블을 관리한다.
- 달력 특성상 과거 데이터보다는 최근 데이터를 많이 조회할 것이므로 음.. 어케해야 하지? 메이비 캐싱? 
- 외부 캘린더 일정은 캐시를 통해 조회를 개선할 수 있겠다.
- 서버도 AWS 뿐만 아니라 다양한 곳의 서버를 나눠 사용해서 한 곳에 문제가 생기더라도 서비스를 제공할 수 있게 한다.

**Comment by gudonghee2000** [comment]
1. 가장 앞에 H/W 성능이 좋은 L4 Switch를 사용한다.

2. 기능별로 WAS를 4대씩 띄운다.

3. 기능별로 4대씩 띄운 WAS에 WS를 로드 밸런서로 둔다.  

4. DB에 대해서 클러스터링을 한다. => 월별로 데이터 파티셔닝 처리를 한다.

5. 클러스터링한 DB에 레플리케이션한 DB를 4대 둔다. 

6. 레플리케이션한 DB를 Group을 기준으로 샤딩하여 테이블 별로 따로 저장한다.

**Comment by summerlunaa** [comment]
![IMG_2D466FEA1E00-1](https://user-images.githubusercontent.com/77425729/196351116-1f330fa6-1531-4468-8dbf-f7c175490fc8.jpeg)
