### ISSUE TITLE
1,000만명이 사용하는 서비스를 목표로 기획을 확장한다.

### ISSUE THREAD

**Issue by devHudi** [woowacourse-teams/2022-dallog#717]
## 🤷 구현할 기능

> 1,000만명이 사용하는 서비스를 목표로 기획을 확장한다. 점진적으로 대상을 넓혀서 서비스 할 수 있도록 계획을 세운다. 사용자를 확보하는데 필요한 전략은 무엇이고 어떤 단계로 확장할 것인지에 대한 계획을 공유한다. 만약 현재는 우테코 내부 인원을 대상으로 서비스를 기획했다면 1차 확장, 2차 확장과 같이 점진적인 계획을 수립한다.

각자의 의견을 본 이슈 코멘트로 남겨주세요.

## 🔨 상세 작업 내용

- [x] 1,000만명이 사용하는 서비스를 목표로 기획을 확장한다.
- [x] 6명의 의견을 하나로 합쳐 정리한다.

**Comment by hyeonic** [comment]
우선 천만명이 사용하면 너무 행복할 것 같다. 

우선 우리는 하나의 데이터베이스를 활용하고 있다. 만약 스케일 아웃을 한 애플리케이션 서버가 늘어날 수록 한정된 커넥션을 가진 데이터베이스는 병목 현상이 일어나게 될 것이다. 데이터베이스의 쿼리 처리 시간을 조절 하던, 스케일 아웃을 하던 추가적인 조치가 필요하다.

데이터베이스의 쿼리 튜닝에 가장 중요한 부분은 바로 디스크 I/O를 줄이는 것이다. 디스크 I/O를 줄이는 방법으로는 인덱스를 적절히 활용하는 것이다. 

스케일 아웃하는 방법도 있다. 

- 파티셔닝
- 레플리케이션
- 클러스터링
- 샤딩
- …

우리는 데이터베이스의 일련의 비즈니스 로직을 트랜잭션 단위로 진행학하고 있다. 트랜잭션이 마무리되면 커넥션 풀에 커넥션을 반납하게 된다. 만약 이 트랜잭션 처리 시간이 길어질수록 커넥션을 얻기 위한 요청은 막연하게 기다릴 뿐이다.

이러한 트랜잭션 처리 시간을 최소화 하는 것도 수 많은 동시 요청을 감당할 수 있는 방법 중 하나이다. 병목이 생기는 지점을 잘 확인하고 사전에 대비한다.

애플리케이션 서버를 확장하는 것 vs 데이터베이스 서버를 확장하는 것

우선 순위가 높은 것은 데이터베이스라고 생각한다. 외부 리소스를 제외한 특정 요청에서 가장 오랜 시간이 걸리는 부분은 바로 데이터베이스와의 통신 시간이라 생각한다. 이러한 데이터베이스가 안정적으로 확장되어야 데이터베이스를 사용하는 애플리케이션도 부담없이 확장될 수 있다.

달록은 외부 리소스를 요청하여 사용하고 있다. 1000만명이 넘는 사용자가 사용할 경우 대부분의 사용자는 외부 리소스를 요청하게 될 것이다. 우리는 일정 정보를 얻기 위해 매번 외부 리소스 요청을 진행해야 한다.

외부 요청으로 부터 응답을 받기 까지의 시간이 추가적으로 소요된다. 그렇기 때문에 우리는 외부 요청에서 오는 데이터를 적절히 캐싱하여 추가적인 요청을 방지해야 한다.

이러한 캐시 서버는 redis를 활용할 수 있다. 특정 외부 캘린더 id를 기반으로 일정 정보를 캐싱하면 해당 캘린더를 구독한 사용자의 요청은 캐싱된 데이터를 재사용할 것이다. 다만 개인 일정의 경우 자신만 조회할 수 있기 때문에 캐싱이 무의미 해질 수 있다.

**Comment by devHudi** [comment]
1. 현재는 우테코 내부에서만 사용하도록 기획하여 그룹 기능이 존재하지 않다. 카테고리의 상위 개념인 '조직' 을 도입하여, 여러 단체에서 사용할 수 있도록 개선할 예정.
2. 현재는 구글 캘린더만 임포트 가능한데, 나중에는 여러 벤더의 캘린더(네이버, 카카오, 애플 등)를 불러올 수 있도록 개선할 예정. 
3. 현재 외부 캘린더를 임포트하는 것만 가능한데, 나중에는 외부 캘린더에 달록의 일정을 익스포트하는 기능을 만들면 좋겠다.
4. Open API를 열어두어 여러 우테코 서비스에서 발생한 일정을 달록에 저장할 수 있도록 만든다.
5. 팔로우 기능을 통해 조직 내 구성원간의 일정을 조회하고 조율할 수 있는 기능을 추가한다.
6. 슬랙 등 메신저 서비스와 연동하여 일정 미리 알림 기능을 구현한다.
7. 카테고리나 일정에 댓글을 달수 있는 기능을 추가하여 협업 기능을 강화한다.

어렵네요 생각보다...

**Comment by hyeonic** [comment]
1. 특정 조직에 소속된 카테고리를 구독할 수 있게 만든다.
2. 개인 사용자는 여러 조직에 소속될 수 있으며, 조직 별 사이드바 아코디언이 나뉘어 진다.
3. 구글 캘린더에 export하는 기능을 추가한다.
4. 알림 기능을 통해 특정 카테고리의 일정이 추가되면 알림을 보내도록한다.
5. 일정 내에 구독한 구성원은 댓글을 남길 수 있도록 한다. 그날 급한 일정이 생길 경우 댓글에 남기는 용도로 활용할 수 있을 것 같다.
6. 스마트폰에서 쉽게 확인할 수 있는 모바일 앱 혹은 위젯을 추가한다.
7. OAuth 서버를 운영하여 다른 앱 혹은 서비스와 연동할 수 있도록 한다.

**Comment by jhy979** [comment]
1. 로그인 하고 가장 먼저 속해 있는 그룹을 선택할 수 있도록 한다
2. 구글 말고도 다른 캘린더와 연동할 수 있도록 한다.
3. 알림 기능을 추가한다. (실시간 발생하는 이벤트에 대해서도 바로 확인 가능)
4. 모바일 환경에서도 확인 가능하도록 반응형과 PWA를 진행한다.
5. 현재 ADMIN과 NONE으로만 구분된 회원을 여러 단계별로 역할로 구분할 수 있도록 한다.

**Comment by summerlunaa** [comment]
- 카테고리 상위의 그룹을 만들어 그룹끼리 카테고리를 공유할 수 있도록 한다.
- 사용자를 확보하기 위해서는 외부 일정 import 및 export, 모바일 사용성 개선, 위젯 설치 등의 기능이 추가되면 좋을 것 같다.

**Comment by daaaayeah** [comment]
- 일주일별, 일별 캘린더
- 드래그로 일정 추가
- 드래그로 일정 이동
- 날짜 드롭다운으로 변경
- 카테고리 순서 바꾸기
- 공개 / 비공개 카테고리
- 공개 / 비공개 일정
- 다른 사용자의 캘린더 조회
- 일정 조율 (구독자의 가능한 시간 모아서 보여주기)
- 소셜 로그인 확대

**Comment by gudonghee2000** [comment]
- 다른 사용자 프로필 조회
- 다른 사용자 캘린더 조회
- 반복 일정
- 구글 export 기능

**Comment by daaaayeah** [comment]
<img width="311" alt="스크린샷 2022-10-14 14 13 11" src="https://user-images.githubusercontent.com/52729559/195767333-fd14fbe9-1fb8-4587-bc87-cfcf20c67984.png">
뿡뿡이가 좋아요 🥕

**Comment by devHudi** [comment]
미로에 정리해두었습니다.
