### ISSUE TITLE
event를 통해 member와 auth의 다른 도메인 패키지에 대한 의존성을 제거한다.

### ISSUE THREAD

**Issue by summerlunaa** [woowacourse-teams/2022-dallog#902]
## 🤷 구현할 기능

- member에서 category role type에 대한 의존성 제거
- event를 통해 auth에서 member를 제외한 다른 도메인의 의존성 제거

## 🔨 상세 작업 내용

- [ ] MemberService의 findSubscriber 메서드를 categoryRole 쪽으로 이동
- [ ] AuthService에서 멤버 가입 시 이벤트를 발행하는 것으로 다른 도메인에 대한 의존성 제거

## ⏰ 예상 소요 기간
4시간

**Comment by devHudi** [comment]
욜

**Comment by summerlunaa** [comment]
이벤트를 사용하는 경우 테스트를 어디서 해야 할까?

1. 이벤트를 발행하는 곳에서 통합적으로 테스트를 진행한다.
2. 발행하는 곳에서는 이벤트가 잘 등록되었는지만 테스트한다. 이벤트 로직에 대한 테스트는 이벤트 리스너 쪽에서 각자 진행한다.

흠 1번은 패키지 분리라는 관점에서 안 좋은 것 같아요. 테스트에서 멤버 테스트가 다른 도메인을 알아야 하니까요. 그리고 멤버 입장에서는 그냥 "나 생성됐다~"만 던지는데 어떤 추가적인 이벤트가 발생하는지 전부 파악해야 하는 통합 테스트가 맞나? 하는 생각이 드네여

근데 또 2번은 이벤트 로직만 테스트할 수 있고 이 메서드가 이벤트에 의해 유기적으로 잘 동작하는지를 테스트할 수 없는 것 같은 느낌?

1번과 2번을 둘 다 해야할까요? 여러분의 생각은 어떠신가요?

**Comment by devHudi** [comment]
이벤트라는게 두 컴포넌트간의 결합을 느슨히 만드는거라고 생각해서 저는 2번에 손을 들어주고 싶은...데 사실 통합 테스트도 필요하다고는 생각합니다 1번! 테스트의 관심사는 내가 의도한대로 기능이 잘 굴러가냐니까, 테스트에서는 다른 도메인을 알고 모르고가 큰 상관없다고 생각합니다. 다만 이벤트를 써본적이 없어서 테스트코드가 어떻게 생길지는 잘 상상이 안가네요 ㅎㅎ

**Comment by hyeonic** [comment]
이벤트 생성 주체는 그냥 `이벤트 발생했어!`만 검증해도 좋을 것 같아요. 통합 테스트는 현재 ServiceTest와 인수 테스트에서 진행하고 있지만 실질적으로 유기적으로 확인할 수 있는 것은 인수테스트 라고 생각하거든요! 서비스 계층에서는 이벤트가 정상적으로 동작하는지 까지는 테스트하지 않아도 좋지 않을까 판단합니다.
